### PR TITLE
Add Support for USMC MCCAST formatted POAM export in STIG Manager

### PR DESCRIPTION
**Pull request by whalenda**
Closes https://github.com/NUWCDIVNPT/stig-manager/issues/1174 by adding support for exporting POAMs in MCCAST format. Adds a template .xlsx file for the MCCAST format, necessary API support to populate the template on request, and updates the Web UI to allow for the selection of either POAM format on export.

### CODE REVIEW

**Comment by whalenda** [comment]
I put this up as a draft, as I'm still working out the test cases for the API updates, however I've added my email to the Contributors.md file whenever you have the opportunity to validate it.  Thanks again for the help @cd-rite!

**Comment by csmig** [comment]
It's looking very good, thanks much for the contribution. I did a first pass over the code with @cd-rite today, we can provide more detailed feedback in a bit. Chris can also explain our still developing processes around this, our first community contribution. Welcome aboard!

**Comment by cd-rite** [comment]
Hi @whalenda I've pushed a few changes to your branch:

- Removed a few out-of-scope changes
- Added poam type to generated filename
- Added an enum restricting poam format to either "EMASS" or "MCCAST"
- Set "EMASS" as the default if no format specified
- Some basic restrictions on the size of the query params to this endpoint (basically, set maxLength of strings to 255 chars)

If you are happy with these changes, you can hit the "Ready for Review" button on this PR, and then @csmig should be able to add any Review comments.
Thanks!

**Comment by csmig** [comment]
Thanks again for the contribution. I've added a couple more commits, one just merges against the current HEAD of main. The other heavily refactors the UI source so it follows our current best practices. We hadn't touched these files in years and they needed better organization. The UI files are hopefully more maintainable now, BZs to @whalenda for understanding the logic in the originals.

I also added the ability in the browser to remember the last POAM format generated and open the POAM options with that format pre-selected.

I made minor changes to the API code, mostly to simplify and for readability.

**Pull request merged**
